name: tfc
description: A Clean Flutter Production Boilerplate.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # UI libs
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  another_flushbar: ^1.10.29

  # Localization
  easy_localization: ^3.0.0

  # Testing
  mockito: ^5.1.0

  # Datasource
  dio: ^4.0.6
  shared_preferences: ^2.0.15

  # Architecture libs
  go_router: ^5.1.5
  provider: ^6.0.3

  # Helper
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
